# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pecavalc <pecavalc@student.42berlin.de>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/08 18:03:57 by pecavalc          #+#    #+#              #
#    Updated: 2025/07/11 15:04:25 by pecavalc         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Library build

NAME = libftprintf.a
	
SRCS_DIR = srcs
OBJS_DIR = objs

SRCS =  convert_arg.c \
		ft_printf.c \
		prefix_and_print_ptr.c \
		print_char.c \
		print_hex_lowcase_nbr.c \
		print_hex_uppercase_nbr.c \
		print_nbr.c \
		print_str.c \
		print_unsigned_nbr.c 

OBJS = $(patsubst %.c,$(OBJS_DIR)/%.o,$(SRCS))

PUB_HEADER = include/ft_printf.h
PRIV_HEADER = srcs/ft_printf_private.h

CFLAGS = -Wall -Wextra -Werror -c -I. -Isrcs

all: $(NAME)

$(NAME): $(OBJS) $(PUB_HEADER) $(PRIV_HEADER)
	ar rcs $@ $^ 

$(OBJS_DIR)/%.o: $(SRCS_DIR)/%.c
	mkdir -p $(OBJS_DIR)
	cc $(CFLAGS) $< -o $@

# Unit test - build and run

TEST_NAME = test_ft_printf
TEST_DIR = tests
TEST_SRCS = $(TEST_DIR)/test_ft_printf.c
TEST_OBJS = $(TEST_DIR)/test_ft_printf.o

test: $(TEST_NAME)
	./$(TEST_NAME)

$(TEST_NAME): $(TEST_OBJS) $(NAME)
	cc -Wall -Wextra -Werror -Iinclude -o $@ $^ 

$(TEST_OBJS): $(TEST_SRCS) $(PUB_HEADER)
	cc -Wall -Wextra -Werror -Iinclude -c $< -o $@

# Clean

clean:
	rm -f $(OBJS) $(TEST_OBJS)
	rm -rf $(OBJS_DIR)

fclean: clean
	rm -f $(NAME) $(TEST_NAME)

re: fclean all

.PHONY: all clean fclean re test